### ISSUE TITLE
Why running torch_mps and torch_cpu with i386/Rosetta2?

### ISSUE THREAD

**Issue by ivanfioravanti** [TristanBilot/mlx-GCN#1]
Hi @TristanBilot thanks for the great repo!
I tested this on M2 Ultra and M3 Max and both torch_mps and torch_cpu were much faster because I executed them in arm64. 
Why are you suggesting to test them using i386?

![M2 Ultra](https://github.com/TristanBilot/mlx-GCN/assets/1069210/4b025dff-e0aa-4f99-a1bc-0175a9f4897f)
![M3 Max](https://github.com/TristanBilot/mlx-GCN/assets/1069210/67a85113-292a-4f19-b6e9-1882d7c31f05)

**Comment by TristanBilot** [comment]
Hi @ivanfioravanti, thank you for having taking the time to run your own experiments locally.
Unfortunately I didn't achieve to run torch mps experiments within an arm env, this is why I don't explore this scenario here, could you tell me how to reproduce your experiments so that I can update the bench :)

**Comment by TristanBilot** [comment]
I finally achieved to make mps work with arm but I end up with 20-21ms for MPS (which is still 2x faster than the i386). The difference between my M1 Pro and your M2 Ultra and M3 Max is impressive, do you authorise me to use your stats so that I can update the benchmark accordingly?

**Comment by ivanfioravanti** [comment]
Absolutely yes! And thanks for the repo, it made benchmark tests ultra fast. 
2x faster not bad!

**Comment by TristanBilot** [comment]
Hi @ivanfioravanti, I hope you are doing well :)
I just created [another repo](https://github.com/TristanBilot/mlx-benchmark) dedicated to mlx benchmarks, and I wonder if you would be interested in running the benchmark locally on your M2 Ultra and M3 Max chips?

**Comment by ivanfioravanti** [comment]
Sure! Stay tuned for the results

**Comment by ivanfioravanti** [comment]
I will post an issue on the other repo @TristanBilot I see you change the logic of computing v[h] = (v["mps"] / v["mlx_gpu"] - 1) + 1 after posting your results in benchmarks for M1 Pro
